name: Azure Bootstrap and Deploy

on:
  push:
    branches:
      - dev
      - qa
      - prod
      - master
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment (dev, qa, prod)"
        required: false

jobs:
  bootstrap-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Set TF_ENV variable
        id: setenv
        run: |
          if [[ -n "${{ github.event.inputs.environment }}" ]]; then
            echo "TF_ENV=${{ github.event.inputs.environment }}" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF##*/}" == "dev" ]]; then
            echo "TF_ENV=dev" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF##*/}" == "qa" ]]; then
            echo "TF_ENV=qa" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF##*/}" == "main" || "${GITHUB_REF##*/}" == "master" ]]; then
            echo "TF_ENV=prod" >> $GITHUB_ENV
          else
            echo "TF_ENV=dev" >> $GITHUB_ENV
          fi

      - name: Show selected environment
        run: |
          echo "Running for environment: $TF_ENV"

      - name: Load environment vars
        run: |
          echo "Loading env/${TF_ENV}.env"
          cat env/
